### ISSUE TITLE
feat: multiple labels

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#128]
Would be nice to have the option to set multiple labels (String Array) instead of just one label for a runner.

**Comment by kichik** [comment]
Can you help me understand what the use case would be here? Converting it to a string array may require a breaking change if JSII doesn't allow both string and string array at the same time.

BTW, you can create multiple providers with the same builder if you're trying to save on build time.

```
const windowsImageBuilder = new ContainerImageBuilder(stack, 'Windows Image Builder', {
    architecture: Architecture.X86_64,
    os: Os.WINDOWS,
});
new GitHubRunners(stack, 'runners', {
    providers: [
        new CodeBuildRunner(stack, 'CodeBuildWindows', {
            label: 'codebuild-windows-x64',
            computeType: codebuild.ComputeType.MEDIUM,
            imageBuilder: windowsImageBuilder,
        }),
        new CodeBuildRunner(stack, 'CodeBuildWindows2', {
            label: 'codebuild-windows-x64-large',
            computeType: codebuild.ComputeType.LARGE,
            imageBuilder: windowsImageBuilder,
        }),
    ],
});
```

**Comment by pharindoko** [comment]
hmm would it be an option to support a comma separated list
e.g.
rename label property to labels and settings multiple values delimited by comma ?

```typescript
labels: "codebuild,windows,large,department-a"
```

**Comment by kichik** [comment]
That's possible. Can you please help me understand why this is needed first? I'm struggling to see the use case for this.

**Comment by pharindoko** [comment]
Having different organizations in our gh environment I think it would be nice to add a label for the department/org and the instance type as well...especially when more and more people start to create their own runners...

**Comment by kichik** [comment]
So the provider would require all labels or just one of the labels? Is it `AND` or `OR`? If it's `AND`, why is a label such as `ORG_NAME-INSTANCE_TYPE` not good?

**Comment by christophgysin** [comment]
It's AND, see:
https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow

It's useful if you have multiple runners, and a job doesn't have strict requirements and can e.g. run on any runner with label `linux`, whereas another can run only on `node-16.x`.

But I'm not sure how useful this is in this project, since the runners are created on demand. The above makes more sense with a fleet of permanent runners, and jobs can use labels to filter which ones satisfy its requirements.

Using this project, a job can request specifically any predefined runner using a single label, which is then provisioned to run just that job.

**Comment by kichik** [comment]
Exactly, this is about starting runners. `OR` would be useful if you want different labels to be able to get the same provider, but can also be addressed with the code from my original comment. `AND` is what I'm struggling to see the use for. The only reason I could think of is having a big existing set of already written workflows that you don't want to have to convert. Is that what's happening? Do you have multiple runners with the same instance size and different configuration per organization?

I'm leaning towards not adding this feature to keep things simple. But I'm willing to be convinced otherwise.

@christophgysin and @pharindoko, do you two have the same need here or are you unrelated?

**Comment by pharindoko** [comment]
@kichik for me it`s more about readability.
Github provides the possibility to add multiple tags to a runner. So why not use it.
When I have to add a string with deparment-os-version-size-...etc. that is specific but hard to read in my eyes.
And I want to avoid having a strict naming convention to use for our department.

**Comment by kichik** [comment]
Ok, I think I can see your point now. Let me experiment with some options.
