### ISSUE TITLE
bug: ContainerImageBuilder - cannot find image for Windows

### ISSUE THREAD

**Issue by pharindoko** [CloudSnorkel/cdk-github-runners#130]
Hey @kichik,

can\`t get that image - maybe because I`m in another region .. eu-central-1
I wanted to build a windows container image for codebuild ...

**code**
```typescript
    const windowsDefaultImage = new ContainerImageBuilder(
      this,
      `${props.serviceName}-${props.stage}-windows-image`,
      {
        architecture: Architecture.X86_64,
        os: Os.WINDOWS,
        runnerVersion: RunnerVersion.latest(),
        rebuildInterval: Duration.days(14),
        instanceType: ec2.InstanceType.of(
          ec2.InstanceClass.T3A,
          ec2.InstanceSize.LARGE
        ),
      }
    );
```

**error**:
```bash
The following required resource 'Image' cannot be found: 'arn:aws:imagebuilder:us-east-1:aws:image/windows-server-20
19-x86-core-ltsc2019-amd64/2020.12.8'
```

**Comment by kichik** [comment]
Oops

**Comment by kichik** [comment]
CodeBuild doesn't seem to support Windows on eu-central-1. The closest is eu-west-1. But even there the image we need doesn't exist.

https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

Fargate does support Windows on all regions except China. EC2 is also coming soon and supports Windows.

If you still want to use CodeBuild, I'm pushing a fix to use an image from Microsoft instead of Image Builder. That's where Image Builder gets the image anyway. I've also added an option to choose your own parent image when needed.

**Comment by pharindoko** [comment]
that`s really nice. yes I wanted to use codebuild for that. I`m surprised that the codebuild images are not available in eu-central-1 but you`re right...
