### ISSUE TITLE
Default configuration quickly runs out of Lambda Hyperplane ENIs

### ISSUE THREAD

**Issue by quad** [CloudSnorkel/cdk-github-runners#332]
Each (lambda version, security group, subnet) triplet uses a hyperplane ENI.

Our (I suspect not abnormal?) configuration looks like the following:
- 12 lambda functions
  - 5 default (token, delete, webhook, setup, status)
  - 1 delete AMI
  - 1 AWS image builder
  - 1 update
  - 1 AWS
  - 1 runner
  - 1 log retention
  - 1 build image
- VPCs are multi-AZ with 3 subnets
- And a security group per high-level CDK construct
  1. Each codebuild runner
  2. Each image builder
  3. Each lambda runner
  4. Each EC2 runner
  5. Each AMI builder
  6. And the top-level GithubRunners

This caused us to hit our hyperplane ENI limits. (See: https://aws.plainenglish.io/dealing-with-you-have-exceeded-the-maximum-limit-for-hyperplane-enis-for-your-account-223147e7ab64)

But each of our security groups were identical! Essentially: `new SecurityGroup(this, 'runners security group', { vpc });`

So we went through every instantiated construct and ensured the `securityGroup` or `securityGroups` parameters were set the same, single, shared security group.

I think this is reasonable default behaviour though? Would it be possible to have done upstream?

**Comment by kichik** [comment]
That's surprising to learn as basically every CDK construct in general creates its own security group.

Do you know if it's just a Lambda issue or the other services you mentioned too? The only Lambda functions that should be running in a VPC are token retriever, delete runner, status, setup, and idle reaper, as they can deal with GitHub Enterprise Server. And even then you would supply a single security group to all of them so they can connect to GitHub Enterprise Server. Lambda runner can also be configured to use VPC. All other Lambda functions don't even have the option to run in VPC and therefore can't have security groups attached.

We can probably optimize this a bit by using a single security group here instead of `undefined` that will cause every Lambda function to create its own security group:

https://github.com/CloudSnorkel/cdk-github-runners/blob/c7313ac9dc30e74cf47e1eb4a8869bfddcc3a7b6/src/runner.ts#L254

But since passing a security group is the only way to configure those Lambda functions to access GitHub Enterprise Server, when will this default even be used?

> But each of our security groups were identical! Essentially: `new SecurityGroup(this, 'runners security group', { vpc });`

They are created identical, but keeping them separate allows the user to then allow access to/from the specific security group without affecting all the other security groups. For example, you may want different access rules for different runner providers. Maybe one provider is for development and one is for production.

**Comment by quad** [comment]
> Do you know if it's just a Lambda issue or the other services you mentioned too? 

It's only a Lambda issue.

> The only Lambda functions that should be running in a VPC are token retriever, delete runner, status, setup, and idle reaper, as they can deal with GitHub Enterprise Server. And even then you would supply a single security group to all of them so they can connect to GitHub Enterprise Server. Lambda runner can also be configured to use VPC. All other Lambda functions don't even have the option to run in VPC and therefore can't have security groups attached.

We supplied a single security group to all of them! That's how we solved our problem.

> > But each of our security groups were identical! Essentially: `new SecurityGroup(this, 'runners security group', { vpc });`
> 
> They are created identical, but keeping them separate allows the user to then allow access to/from the specific security group without affecting all the other security groups. For example, you may want different access rules for different runner providers. Maybe one provider is for development and one is for production.

I'm suggesting the default be changed. I'd expect that we can still manually specify a security group for when we want custom rules.

**Comment by kichik** [comment]
> I'm suggesting the default be changed. I'd expect that we can still manually specify a security group for when we want custom rules.

The point I was trying to make is that you would always specify a security group. Do you mind sharing the scenario where you weren't so I can understand the issue better? Why put the management Lambdas in a VPC if not for them to access GitHub Enterprise Server?
