### ISSUE TITLE
Update broke Lambda Runners

### ISSUE THREAD

**Issue by QuinnyPig** [CloudSnorkel/cdk-github-runners#420]
Just upgraded for the first time in half a year; now the Lambda runner is dying instantly with zero visibility, almost like the entrypoint is wrong. Help?

My code: 

```
import * as cdk from 'aws-cdk-lib';
import { Size, Tags } from 'aws-cdk-lib';
import { Architecture, CodeBuildRunnerImageBuilder, CodeBuildRunnerProvider, GitHubRunners, LambdaRunnerProvider, Os } from '@cloudsnorkel/cdk-github-runners';

const app = new cdk.App();
const stack = new cdk.Stack(
  app,
  'github-runners',
  {
    env: {
      account: process.env.CDK_DEFAULT_ACCOUNT,
      region: process.env.CDK_DEFAULT_REGION,
    },
  },
);

const myBuilder = CodeBuildRunnerProvider.imageBuilder(stack, 'image builder', {
  architecture: Architecture.ARM64,
  os: Os.LINUX_UBUNTU
})

// create a custom Lambda provider
const myProvider = new LambdaRunnerProvider(stack, 'lambda runner', {
  labels: ['lambda-runner'],
  ephemeralStorageSize: Size.gibibytes(2),
  imageBuilder: myBuilder,
},

);

// create the runner infrastructure
new GitHubRunners(
  stack,
  'runners',
  {
    providers: [myProvider],
  }
);
Tags.of(app).add('project', 'lambda-runner');

app.synth();
```

**Comment by kichik** [comment]
The code in your post uses `CodeBuildRunnerProvider.imageBuilder()` instead of `LambdaRunnerProvider.imageBuilder()` so not all the required components are there. Specifically our wrapper that calls the runner from Lambda is not included and that will trigger `Error: Runtime exited without providing a reason Runtime.ExitError` as seen in the logs.

You can technically add the component yourself with the following, but it's best to use the right base image builder.

```
myBuilder.addComponent(RunnerImageComponent.lambdaEntrypoint());
```

There is also an issue where we expect you to use `Os.LINUX_AMAZON_2` (or leave it out as it's the default). We always use Amazon Linux 2 base docker image right now.

Finally it looks like we're using node14 as the base image for this. That should definitely be updated.

The last two can be addressed with:

```
const myBuilder = LambdaRunnerProvider.imageBuilder(stack, 'image builder', {
  architecture: Architecture.ARM64,
  os: Os.LINUX_UBUNTU,
  baseDockerImage: 'a docker image that has ubuntu and lambda runtime (we use public.ecr.aws/lambda/nodejs:14-arm64 by default)',
});
```
