### ISSUE TITLE
CodeBuild runner: COMMAND_EXECUTION_ERROR: Failure in executing runner configuration command with exit status 1

### ISSUE THREAD

**Issue by hratio** [CloudSnorkel/cdk-github-runners#655]
Builds unexpectedly started failing during the installation phase, with the following command timing out:

```bash
COMMAND_EXECUTION_ERROR: Error while executing command: 
sudo -Hu runner /home/runner/config.sh --unattended --url "${REGISTRATION_URL}" --token "${RUNNER_TOKEN}" --ephemeral --work _work --labels "${RUNNER_LABEL},cdkghr:started:`date +%s`" ${RUNNER_FLAGS} --name "${RUNNER_NAME}" ${RUNNER_GROUP}
Reason: exit status 1
```

I'm on runner version 2.320.0.
No infrastructure changes have been applied since it worked and status.json shows no errors. 
No known changes has been done in GitHub or on the Runner App.

Is there a way to get more info on the ./config.sh error to be able to pinpoint the origin?

**Comment by kichik** [comment]
When you say it's timing out, do you mean your own jobs because no runner gets assigned to them? The log you attached seems to suggest `config.sh` is failing and not timing out.

`config.sh` and `run.sh` save their logs to `/home/runner/_diag/`. We don't currently collect those anywhere. I would suggest you first try upgrading to 2.321.0. If that doesn't work, editing the CodeBuild project and dumping those logs after `config.sh` might be the quickest way to get an answer.
